apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ssrf-allowlist-role
rules:
  - apiGroups: [ "" ]
    resources: [ "pods" ]
    verbs: [ "get", "watch", "list" ]
  - apiGroups: [ "inference.networking.x-k8s.io" ]
    resources: [ "inferencepools" ]
    verbs: [ "get", "watch", "list" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ssrf-allowlist-rolebinding
subjects:
  - kind: ServiceAccount
    name: placeholder
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: ssrf-allowlist-role
  apiGroup: rbac.authorization.k8s.io

